---
- name: Setup local users
  user:
    name:         "{{ item.key }}"
    state:        "{{ item.value.state | default('present') }}"
    uid:          "{{ item.value.uid | default(omit) }}"
    group:        "{{ item.value.group | default(omit) }}"
    shell:        "{{ item.value.shell | default(omit) }}"
    createhome:   "{{ item.value.createhome | default('yes') }}"
    system:       "{{ item.value.system | default(omit) }}"
  with_dict:      "{{ custom_users | default({}) }}"
- name: Setup authorized keys
  authorized_key:
    user:         "{{ item.key }}"
    state:        "{{ item.value.state | default('present') }}"
    key_options:  "{{ item.value.key_options | default(omit) }}"
    key:          "{{ lookup('file', item.value.file | default(lookup('env', 'HOME') + '/.ssh/id_rsa.pub')) }}"
  with_dict:      "{{ custom_authorized_keys | default({}) }}"
  ignore_errors:  yes
- name: Setup sudo
  lineinfile:
    dest:         "{{ item.value.file | default('/etc/sudoers.d/20-' + item.key) }}"
    state:        "{{ item.value.state | default('present') }}"
    create:       yes
    regexp:       "{{ item.key + '.*' }}"
    line:         "{{ item.key }} {{ item.value.host | default('ALL') }}={{ item.value.operator | default('(ALL)') }} {{ item.value.tag | default('NOPASSWD') }}:{{ item.value.command | default('ALL') }}"
  with_dict:      "{{ custom_sudoers | default({}) }}"
  ignore_errors:  yes
