---
custom_packages:
  tmux:     {}
  htop:     {}
  mlocate:  {}
custom_users:
  raymond:
    group: users
custom_authorized_keys:
  raymond: {} # This will use the local .ssh/.id_rsa.pub
custom_sudoers:
  raymond: {}
